name: Test Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on:
      - self-hosted
      - Linux
      - X64

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: |
          pwd
          ls -la
          echo "Runner is working!"
