name: Deploy to Tomcat via Manager API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on:
      - self-hosted
      - Linux
      - X64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Runner
        run: |
          echo "Runner Name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          pwd
          ls -la

      - name: Check Java
        run: java -version

      - name: Check Maven
        run: mvn -version

      - name: Build WAR
        run: mvn clean package -DskipTests

      - name: Deploy WAR
        run: |
          WAR_FILE=$(find target -name "*.war" | head -n 1)
          APP_NAME=madhuapp

          curl -u "${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }}" \
            --upload-file "$WAR_FILE" \
            "http://${{ secrets.TOMCAT_HOST }}:8081/manager/text/deploy?path=/$APP_NAME&update=true"
